version: '3'

x-uffizzi:
  ingress:
    service: postgraphile
    port: 5000

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uffizzi
    ports:
      - "5432:5432"

  postgraphile:
    image: "${POSTGRAPHILE_IMAGE}"
    depends_on:
      - db
    ports:
      - "5000:5000"
    command:
            [
              "--retry-on-init-fail",
              "--connection",
              "postgres://postgres:postgres@localhost:5432/uffizzi",
              "--port",
              "5000",
              "--schema",
              "public",
            ]